-- ════════════════════════════════════════════════════════
-- 004 — ANULADA. NO APLICAR.
-- ════════════════════════════════════════════════════════
--
-- Esta migración fue escrita el 2026-08-05 para cerrar un supuesto acceso
-- anónimo de escritura a `noticias`. Se verificó contra la base viva el
-- 2026-08-10 y ESE AGUJERO NO EXISTE. El SQL fue removido a propósito:
-- el archivo queda solo como registro. Correrlo hoy no hace nada.
--
-- ─── POR QUÉ ESTABA MAL ──────────────────────────────────
-- Se escribió leyendo `sql/setup/noticias_setup.sql` (el archivo de setup del
-- repo) en lugar de consultar `pg_policies` en la base real. El archivo de
-- setup estaba desactualizado: describía las políticas originales
-- ("Anon full access noticias", etc.), que en la base ya habían sido
-- reemplazadas por políticas con gate de admin. Ninguna de las tres políticas
-- que esta migración pretendía borrar existe.
--
-- ─── POR QUÉ APLICARLA HABRÍA SIDO PEOR ──────────────────
-- Creaba `Authenticated manage noticias` con:
--     FOR ALL TO authenticated USING (true) WITH CHECK (true)
-- Las políticas RLS se combinan con OR: esa política NO habría reemplazado a
-- las de admin, se habría apilado encima. Resultado: cualquier usuario
-- logueado — incluido un jinete con cuenta de afiliado — habría podido crear,
-- editar y borrar noticias. Lo mismo en storage con las políticas de fotos.
-- La migración habría ABIERTO un permiso, no cerrado uno.
--
-- ─── ESTADO REAL VERIFICADO (2026-08-10) ─────────────────
-- Tabla `noticias` — 5 políticas, todas correctas:
--   Public read published noticias  SELECT  USING (estado = 'publicado')
--   admins ven todas las noticias   SELECT  USING (get_my_rol() = ANY (ARRAY['superadmin','admin']))
--   admins crean noticias           INSERT  WITH CHECK (get_my_rol() = ANY (...))
--   admins editan noticias          UPDATE  USING (get_my_rol() = ANY (...))
--   admins borran noticias          DELETE  USING (get_my_rol() = ANY (...))
--
-- Figuran con rol `{public}`, que NO significa "abierto": la policy aplica a
-- todos los roles y quien decide es la condición interna, que exige admin.
--
-- Storage, bucket `noticias-fotos` (public = true):
--   Admins upload noticias fotos    INSERT  WITH CHECK (bucket_id = 'noticias-fotos'
--                                           AND get_my_rol() = ANY (ARRAY['superadmin','admin']))
--
-- No hay policy SELECT y no hace falta: el bucket es público y se sirve por
-- CDN, sin pasar por RLS. Tampoco hay policy de UPDATE ni de DELETE, y hoy
-- ninguna de las dos ausencias rompe nada: `uploadFotoToStorage()` genera el
-- nombre con Date.now() + random, así que el `upsert:true` nunca llega a
-- hacer UPDATE, y el admin nunca borra fotos de este bucket
-- (`removeGaleriaFoto()` solo las saca del array en memoria). El efecto real
-- es que quedan archivos huérfanos en el bucket — prolijidad, no seguridad.
--
-- ─── LA REGLA QUE SALE DE ACÁ ────────────────────────────
-- Antes de escribir cualquier migración de RLS, leer las políticas VIVAS:
--
--   SELECT schemaname, tablename, policyname, cmd, roles, qual, with_check
--     FROM pg_policies
--    WHERE tablename = '<tabla>'
--    ORDER BY schemaname, tablename, policyname;
--
-- Los archivos de setup del repo son historia, no estado. Y `roles` por sí
-- solo no dice si una policy es permisiva: hay que leer `qual`/`with_check`.
-- ════════════════════════════════════════════════════════
